name: app_cosmetic
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  expansion_tile_card: ^3.0.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/facebook.png
    - assets/instagram.png
    - assets/twitter.png
    - lib/img/taybaochet.png
