name: app_cosmetic
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  banner_carousel: ^1.2.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  full_screen_image: ^2.0.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash2.jpg
    - assets/splash3.jpg
    - assets/Lottie/Animation - 1719079023706.json
